language: ruby
bundler_args: "--without system_tests"
before_install: rm Gemfile.lock || true
script: bundle exec rake test
cache: bundler
sudo: required
rvm:
- 2.1.0
env:
- PUPPET_VERSION="~> 4.6.0"
- PUPPET_VERSION="~> 4.7.0"
- PUPPET_VERSION="~> 4.8.0"
- PUPPET_VERSION="~> 4.9.0"
- PUPPET_VERSION="~> 4.10.0"
- PUPPET_VERSION="~> 5.3.0"
